name: mario
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.1.0
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - grpcio=1.62.2
  - importlib-metadata=8.5.0
  - libabseil=20240116.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=14.0.6
  - libffi=3.4.4
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgrpc=1.62.2
  - liblapack=3.9.0
  - libopenblas=0.3.29
  - libprotobuf=4.25.3
  - llvm-openmp=20.1.3
  - markdown=3.6
  - ncurses=6.4
  - openssl=3.5.0
  - packaging=25.0
  - pip=24.2
  - protobuf=4.25.3
  - python=3.8.20
  - python_abi=3.8
  - re2=2022.04.01
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tensorboard=2.17.1
  - tensorboard-data-server=0.7.0
  - tk=8.6.14
  - werkzeug=3.0.6
  - wheel=0.44.0
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - ale-py==0.10.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - decorator==4.4.2
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - einops==0.8.1
      - eval-type-backport==0.2.2
      - farama-notifications==0.0.4
      - filelock==3.16.1
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gym==0.26.2
      - gym-notices==0.0.8
      - gym-super-mario-bros==7.4.0
      - huggingface-hub==0.30.2
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - importlib-resources==6.4.5
      - jinja2==3.1.6
      - kiwisolver==1.4.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - moviepy==1.0.3
      - mpmath==1.3.0
      - nes-py==8.2.1
      - networkx==3.1
      - numpy==1.24.4
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - pandas==2.0.3
      - pillow==10.4.0
      - platformdirs==4.3.6
      - proglog==0.1.11
      - psutil==7.0.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyglet==1.5.21
      - pygments==2.19.1
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==14.0.0
      - safetensors==0.5.3
      - sentry-sdk==2.27.0
      - setproctitle==1.3.6
      - shtab==1.7.2
      - six==1.17.0
      - smmap==5.0.2
      - stable-baselines3==2.4.1
      - sympy==1.13.3
      - tokenizers==0.20.3
      - torch==2.4.1
      - torchvision==0.19.1
      - tqdm==4.67.1
      - transformers==4.46.3
      - typeguard==4.4.0
      - typing-extensions==4.13.2
      - tyro==0.9.19
      - tzdata==2025.2
      - urllib3==2.2.3
      - wandb==0.19.10
      - zipp==3.20.2
